[auth]
username = "allan"
password = "TROCAR_ESSA_SENHA"

[database]
# Para rodar local, use:
mode = "local"

# Para rodar na nuvem com Turso/libSQL, altere para:
# mode = "turso"
# url = "libsql://SEU-BANCO.turso.io"
# auth_token = "SEU_TOKEN_TURSO"
